set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMake")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_DEBUG_POSTFIX "_d")
set(CMAKE_DISABLE_IN_SOURCE_BUILD ON)
set(CMAKE_DISABLE_SOURCE_CHANGES ON)

set(GLFW_BUILD_EXAMPLES				OFF CACHE INTERNAL "Build the GLFW example programs")
set(GLFW_BUILD_TESTS				OFF CACHE INTERNAL "Build the GLFW test programs")
set(GLFW_BUILD_DOCS					OFF CACHE INTERNAL "Build the GLFW documentation")
set(GLFW_INSTALL					OFF CACHE INTERNAL "Generate installation target")
set(BUILD_SHARED_LIBS				OFF CACHE INTERNAL "Build package with shared libraries.")
set(GLM_ENABLE_CXX_20				ON  CACHE INTERNAL "Build glm using c++ 20")
set(SPDLOG_ENABLE_PCH				ON  CACHE INTERNAL "Compile spdlog using precompiled headers")
set(IMGUI_ENABLE_FREETYPE			ON  CACHE INTERNAL "Use freetype in imgui to display fonts")
set(IMGUI_DEFINE_MATH_OPERATORS		ON  CACHE INTERNAL "Use imgui math operators")
set(IMGUI_IMPL_OPENGL_LOADER_GLAD	ON  CACHE INTERNAL "Use opengl loader and glad in imgui project")